import Head from "next/head";
import HomePageContainer from "@/containers/home-page-container";
import styles from "@/styles/main.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Covid App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePageContainer />
      </main>
    </>
  );
}
